site_name: Seeking the Truth
pages:
- [index.md, Home]
- [concept_of_god_in_hinduism.md, Concept of God in Hinduism]
- [sai_baba.md, Sai Baba and His Teachings]
- [jesus_pbuh_and_his_beliefs.md, Jesus (pbuh) and His Teachings]
- [what_did_moses_pbuh_teach_the_jews_according_to_old_testament.md, What did Moses (pbuh) Teach the Jews (According to Old Testament)]
- [why_do_i_believe_in_heaven_and_hell.md, Why do I Believe in Heaven and Hell]
- [history_of_astrology.md, History of Astrology]
theme: readthedocs
