site_name: Seeking the Truth
pages:
- [index.md, Home]
- [concept_of_god_in_hinduism.md, Concept of God in Hinduism]
- [sai_baba.md, Sai Baba and His Teachings]
- [jesus_pbuh_and_his_beliefs.md, Jesus (pbuh) and His Teachings]
- [history_of_astrology.md, History of Astrology]
theme: readthedocs
