site_name: Seeking the Truth
pages:
- [index.md, Home]
- [concept_of_god_in_hinduism.md, Concept of God in Hinduism]
- [sai_baba.md, Sai Baba and His Teachings]
- [about.md, About]
theme: readthedocs
